# Set the base image to Ubuntu
FROM continuumio/miniconda3

RUN conda install -y python=3.6 pandas requests matplotlib pymongo

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt && rm requirements.txt

# this is used to mock http for testing
RUN pip install httpretty nose coverage nose-timer

# Import this to run construct the font-cache
RUN python -c "from matplotlib.font_manager import FontManager"

CMD nosetests -w /pyutil/test --with-coverage --cover-html --cover-erase --cover-package=pyutil --cover-html-dir=/html-coverage --with-timer
