# Set the base image to Ubuntu
FROM continuumio/miniconda3

# lxml is causing a big mess only to make sure the premailer works. This has to be revisited and simplified...
COPY lib/libgcrypt.deb libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb
RUN dpkg -i libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb

RUN conda install -y python=3.6 pandas requests matplotlib pymongo xlrd=1.0.0 jinja2=2.8 xlsxwriter lxml

RUN pip install raven==5.27.1 premailer

# this is used to mock http for testing
RUN pip install httpretty nose coverage nose-timer

# Import this to run construct the font-cache
RUN python -c "from matplotlib.font_manager import FontManager"
